displayName=Spec Regen Completed
author=vividflash
description=Plays a sound when your special attack energy reaches your weapon's cost
tags=special,attack,spec,energy,sound,audio,alert,combat
plugins=com.vividflash.specregencompleted.SpecRegenCompletedPlugin
build=standard
version=0.1
