displayName=Spec Regen Completed
author=vividflash
description=Plays a sound when your spec is ready.
tags=special,attack,spec,energy,sound,audio,alert,combat
plugins=com.vividflash.specregencompleted.SpecRegenCompletedPlugin
build=standard
version=1.0
