/*
 * Copyright (c) 2026, vividflash
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package com.vividflash.specregencompleted;

import java.util.HashMap;
import java.util.Map;
import lombok.Getter;
import net.runelite.api.gameval.ItemID;

/**
 * Weapons with a special attack, and the energy each costs as a percentage of a
 * full bar. Cosmetic recolours, ornament-kit forms, charge tiers and game-mode
 * variants share their weapon's entry, since they share its cost.
 *
 * <p>Costs come from the special attack list on the Old School RuneScape Wiki.
 * Item ids come from matching each weapon's in-game item name against the
 * client's own item cache, so a form the game names differently from its base
 * weapon, as a volcanic abyssal whip or a dragon felling axe is, still lands on
 * the right cost.
 */
@Getter
enum SpecWeapon
{
    ABYSSAL_BLUDGEON(50, ItemID.ABYSSAL_BLUDGEON, ItemID.ABYSSAL_BLUDGEON_1,
        ItemID.ABYSSAL_BLUDGEON_2, ItemID.ABYSSAL_BLUDGEON_3),
    ABYSSAL_DAGGER(25, ItemID.ABYSSAL_DAGGER, ItemID.ABYSSAL_DAGGER_P, ItemID.ABYSSAL_DAGGER_P_,
        ItemID.ABYSSAL_DAGGER_P__, ItemID.BH_ABYSSAL_DAGGER_IMBUE),
    ABYSSAL_TENTACLE(50, ItemID.ABYSSAL_TENTACLE, ItemID.LEAGUE_3_WHIP_TENTACLE),
    ABYSSAL_WHIP(50, ItemID.ABYSSAL_WHIP, ItemID.ABYSSAL_WHIP_LAVA, ItemID.ABYSSAL_WHIP_ICE,
        ItemID.BR_ABYSSAL_WHIP, ItemID.LEAGUE_3_WHIP),
    ACCURSED_SCEPTRE(50, ItemID.WILD_CAVE_ACCURSED_CHARGED,
        ItemID.WILD_CAVE_ACCURSED_CHARGED_RECOL),
    ANCIENT_GODSWORD(50, ItemID.ANCIENT_GODSWORD, ItemID.BR_ANCIENT_GODSWORD),
    ARCLIGHT(50, ItemID.ARCLIGHT),
    ARKAN_BLADE(30, ItemID.ARKAN_BLADE),
    ARMADYL_CROSSBOW(50, ItemID.ACB, ItemID.BR_ACB),
    ARMADYL_GODSWORD(50, ItemID.AGS, ItemID.AGSG, ItemID.BR_AGS, ItemID.ROTTEN_AGS),
    BANDOS_GODSWORD(50, ItemID.BGS, ItemID.BGSG),
    BLISTERWOOD_FLAIL(10, ItemID.BLISTERWOOD_FLAIL),
    BLUE_MOON_SPEAR(50, ItemID.FROSTMOON_SPEAR, ItemID.BR_FROSTMOON_SPEAR),
    BONE_DAGGER(75, ItemID.DTTD_BONE_DAGGER, ItemID.DTTD_BONE_DAGGER_P, ItemID.DTTD_BONE_DAGGER_P_,
        ItemID.DTTD_BONE_DAGGER_P__),
    BRINE_SABRE(75, ItemID.OLAF2_BRINE_SABRE),
    CRIMSON_KISTEN(50, ItemID.CRIMSON_KISTEN),
    CRYSTAL_AXE(100, ItemID.CRYSTAL_AXE, ItemID.GAUNTLET_AXE_HM, ItemID.GAUNTLET_AXE,
        ItemID.CRYSTAL_AXE_2H),
    CRYSTAL_HALBERD(30, ItemID.CRYSTAL_HALBERD_NEW, ItemID.CRYSTAL_HALBERD_1000,
        ItemID.CRYSTAL_HALBERD_900, ItemID.CRYSTAL_HALBERD_800, ItemID.CRYSTAL_HALBERD_700,
        ItemID.CRYSTAL_HALBERD_600, ItemID.CRYSTAL_HALBERD_500, ItemID.CRYSTAL_HALBERD_400,
        ItemID.CRYSTAL_HALBERD_300, ItemID.CRYSTAL_HALBERD_200, ItemID.CRYSTAL_HALBERD_100,
        ItemID.CRYSTAL_HALBERD, ItemID.CRYSTAL_HALBERD_2500),
    CRYSTAL_HARPOON(100, ItemID.CRYSTAL_HARPOON, ItemID.GAUNTLET_HARPOON_HM,
        ItemID.GAUNTLET_HARPOON),
    CRYSTAL_PICKAXE(100, ItemID.CRYSTAL_PICKAXE, ItemID.GAUNTLET_PICKAXE_HM,
        ItemID.GAUNTLET_PICKAXE),
    DARKLIGHT(50, ItemID.DARKLIGHT),
    DARK_BOW(55, ItemID.DARKBOW, ItemID.DARKBOW_GREEN, ItemID.DARKBOW_BLUE, ItemID.DARKBOW_YELLOW,
        ItemID.DARKBOW_WHITE, ItemID.BR_DARKBOW, ItemID.BH_DARKBOW_IMBUE),
    DINH_S_BULWARK(50, ItemID.DINHS_BULWARK, ItemID.DINHS_BULWARK_ORNAMENT),
    DRAGON_2H_SWORD(60, ItemID.DRAGON_2H_SWORD, ItemID.BR_DRAGON_2H,
        ItemID.BH_DRAGON_2H_SWORD_CORRUPTED),
    DRAGON_AXE(100, ItemID.DRAGON_AXE, ItemID.TRAILBLAZER_AXE_NO_INFERNAL, ItemID.DRAGON_AXE_2H,
        ItemID.TRAILBLAZER_RELOADED_AXE_NO_INFERNAL),
    DRAGON_BATTLEAXE(100, ItemID.DRAGON_BATTLEAXE, ItemID.BH_DRAGON_BATTLEAXE_CORRUPTED),
    DRAGON_CLAWS(50, ItemID.DRAGON_CLAWS, ItemID.BR_DRAGON_CLAWS, ItemID.DRAGON_CLAWS_ORNAMENT,
        ItemID.BH_DRAGON_CLAWS_CORRUPTED),
    DRAGON_DAGGER(25, ItemID.DRAGON_DAGGER, ItemID.DRAGON_DAGGER_P, ItemID.DRAGON_DAGGER_P_,
        ItemID.DRAGON_DAGGER_P__, ItemID.BR_DRAGON_DAGGER, ItemID.BH_DRAGON_DAGGER_CORRUPTED),
    DRAGON_HALBERD(30, ItemID.DRAGON_HALBERD, ItemID.BH_DRAGON_HALBERD_CORRUPTED),
    DRAGON_HARPOON(100, ItemID.DRAGON_HARPOON, ItemID.TRAILBLAZER_HARPOON_NO_INFERNAL,
        ItemID.TRAILBLAZER_RELOADED_HARPOON_NO_INFERNAL),
    DRAGON_KNIFE(25, ItemID.DRAGON_KNIFE, ItemID.DRAGON_KNIFE_P, ItemID.DRAGON_KNIFE_P_,
        ItemID.DRAGON_KNIFE_P__, ItemID.BR_DRAGON_KNIFE),
    DRAGON_LONGSWORD(25, ItemID.DRAGON_LONGSWORD, ItemID.BH_DRAGON_LONGSWORD_IMBUE,
        ItemID.BH_DRAGON_LONGSWORD_CORRUPTED),
    DRAGON_MACE(25, ItemID.DRAGON_MACE, ItemID.BH_DRAGON_MACE_IMBUE,
        ItemID.BH_DRAGON_MACE_CORRUPTED),
    DRAGON_PICKAXE(100, ItemID.DRAGON_PICKAXE, ItemID.DRAGON_PICKAXE_PRETTY, ItemID.ZALCANO_PICKAXE,
        ItemID.TRAILBLAZER_PICKAXE_NO_INFERNAL, ItemID.TRAILBLAZER_RELOADED_PICKAXE_NO_INFERNAL),
    DRAGON_SCIMITAR(55, ItemID.DRAGON_SCIMITAR, ItemID.DRAGON_SCIMITAR_ORNAMENT,
        ItemID.BR_DRAGON_SCIMITAR, ItemID.BH_DRAGON_SCIMITAR_CORRUPTED),
    DRAGON_SPEAR(25, ItemID.DRAGON_SPEAR, ItemID.DRAGON_SPEAR_P, ItemID.TBWT_DRAGON_SPEAR_KP,
        ItemID.DRAGON_SPEAR_P_, ItemID.DRAGON_SPEAR_P__, ItemID.BH_DRAGON_SPEAR_CORRUPTED),
    DRAGON_THROWNAXE(25, ItemID.DRAGON_THROWNAXE, ItemID.BR_DRAGON_THROWNAXE),
    DRAGON_WARHAMMER(50, ItemID.DRAGON_WARHAMMER, ItemID.BR_DRAGON_WARHAMMER,
        ItemID.DRAGON_WARHAMMER_ORNAMENT, ItemID.BH_DRAGON_WARHAMMER_CORRUPTED),
    DUAL_MACUAHUITL(25, ItemID.DUAL_MACUAHUITL, ItemID.BR_DUAL_MACUAHUITL),
    ECLIPSE_ATLATL(50, ItemID.ECLIPSE_ATLATL, ItemID.BR_ECLIPSE_ATLATL),
    ELDER_MAUL(50, ItemID.ELDER_MAUL, ItemID.BR_ELDER_MAUL, ItemID.ELDER_MAUL_ORNAMENT),
    ELDRITCH_NIGHTMARE_STAFF(55, ItemID.NIGHTMARE_STAFF_ELDRITCH),
    EMBERLIGHT(50, ItemID.EMBERLIGHT),
    EXCALIBUR(100, ItemID.EXCALIBUR),
    EYE_OF_AYAK(50, ItemID.EYE_OF_AYAK),
    GRANITE_HAMMER(60, ItemID.GRANITE_HAMMER),
    GRANITE_MAUL(60, ItemID.GRANITE_MAUL, ItemID.GRANITE_MAUL_PRETTY, ItemID.BR_GRANITE_MAUL),
    GRANITE_MAUL_ORNATE_HANDLE(50, ItemID.GRANITE_MAUL_PLUS, ItemID.GRANITE_MAUL_PRETTY_PLUS),
    HALLOWED_FLAIL(10, ItemID.HALLOWED_FLAIL),
    HEAVY_BALLISTA(65, ItemID.HEAVY_BALLISTA, ItemID.BR_HEAVY_BALLISTA,
        ItemID.HEAVY_BALLISTA_ORNAMENT),
    INFERNAL_AXE(100, ItemID.INFERNAL_AXE, ItemID.INFERNAL_AXE_EMPTY, ItemID.TRAILBLAZER_AXE,
        ItemID.TRAILBLAZER_AXE_EMPTY, ItemID.TRAILBLAZER_RELOADED_AXE,
        ItemID.TRAILBLAZER_RELOADED_AXE_EMPTY),
    INFERNAL_HARPOON(100, ItemID.INFERNAL_HARPOON, ItemID.INFERNAL_HARPOON_EMPTY,
        ItemID.TRAILBLAZER_HARPOON, ItemID.TRAILBLAZER_HARPOON_EMPTY,
        ItemID.TRAILBLAZER_RELOADED_HARPOON, ItemID.TRAILBLAZER_RELOADED_HARPOON_EMPTY),
    INFERNAL_PICKAXE(100, ItemID.INFERNAL_PICKAXE, ItemID.INFERNAL_PICKAXE_EMPTY,
        ItemID.TRAILBLAZER_PICKAXE, ItemID.TRAILBLAZER_PICKAXE_EMPTY,
        ItemID.TRAILBLAZER_RELOADED_PICKAXE, ItemID.TRAILBLAZER_RELOADED_PICKAXE_EMPTY),
    IVANDIS_FLAIL(10, ItemID.IVANDIS_FLAIL),
    KERIS_PARTISAN_OF_CORRUPTION(75, ItemID.KERIS_PARTISAN_CORRUPTION),
    KERIS_PARTISAN_OF_THE_SUN(75, ItemID.KERIS_PARTISAN_SUN),
    LIGHT_BALLISTA(65, ItemID.LIGHT_BALLISTA, ItemID.BR_LIGHT_BALLISTA),
    MAGIC_LONGBOW(35, ItemID.MAGIC_LONGBOW),
    MAGIC_SHORTBOW(55, ItemID.MAGIC_SHORTBOW, ItemID.BR_MAGIC_BOW),
    MAGIC_SHORTBOW_I(50, ItemID.MAGIC_SHORTBOW_I),
    MORRIGAN_S_JAVELIN(50, ItemID.MORRIGANS_JAVELIN, ItemID.BR_MORRIGANS_JAVELIN,
        ItemID.MORRIGANS_JAVELIN_BH),
    MORRIGAN_S_THROWING_AXE(50, ItemID.MORRIGANS_THROWNAXE, ItemID.MORRIGANS_THROWNAXE_BH),
    NOXIOUS_HALBERD(50, ItemID.NOXIOUS_HALBERD, ItemID.BR_NOXIOUS_HALBERD),
    OSMUMTEN_S_FANG(25, ItemID.OSMUMTENS_FANG, ItemID.OSMUMTENS_FANG_ORNAMENT,
        ItemID.BR_OSMUMTENS_FANG),
    PURGING_STAFF(25, ItemID.PURGING_STAFF, ItemID.BR_PURGING_STAFF),
    ROSEWOOD_BLOWPIPE(25, ItemID.ROSEWOOD_BLOWPIPE, ItemID.ROSEWOOD_BLOWPIPE_EMPTY),
    RUNE_CLAWS(25, ItemID.RUNE_CLAWS),
    RUNE_THROWNAXE(10, ItemID.RUNE_THROWNAXE),
    SARADOMIN_GODSWORD(50, ItemID.SGS, ItemID.SGSG),
    SARADOMIN_SWORD(100, ItemID.SARADOMIN_SWORD),
    SARADOMIN_S_BLESSED_SWORD(65, ItemID.BLESSED_SARADOMIN_SWORD,
        ItemID.BLESSED_SARADOMIN_SWORD_DEGRADED),
    SCORCHING_BOW(25, ItemID.SCORCHING_BOW),
    SOULFLAME_HORN(25, ItemID.SOULFLAME_HORN),
    STAFF_OF_BALANCE(100, ItemID.STAFF_OF_BALANCE),
    STAFF_OF_LIGHT(100, ItemID.STAFF_OF_LIGHT),
    STAFF_OF_THE_DEAD(100, ItemID.SOTD, ItemID.BR_SOTD),
    STATIUS_S_WARHAMMER(35, ItemID.STATIUS_WARHAMMER, ItemID.BR_STATIUS_WARHAMMER,
        ItemID.STATIUS_WARHAMMER_BH),
    SUNSPEAR(50, ItemID.SUNSPEAR),
    THIRD_AGE_AXE(100, ItemID._3A_AXE, ItemID._3A_AXE_2H),
    THIRD_AGE_PICKAXE(100, ItemID._3A_PICKAXE),
    TONALZTICS_OF_RALOS(50, ItemID.TONALZTICS_OF_RALOS_CHARGED),
    TOXIC_BLOWPIPE(50, ItemID.TOXIC_BLOWPIPE_LOADED, ItemID.TOXIC_BLOWPIPE_LOADED_ORNAMENT),
    TOXIC_STAFF_OF_THE_DEAD(100, ItemID.TOXIC_SOTD_CHARGED, ItemID.TOXIC_SOTD_CHARGED_DEADMAN),
    URSINE_CHAINMACE(50, ItemID.WILD_CAVE_URSINE_CHARGED),
    VESTA_S_LONGSWORD(25, ItemID.VESTAS_LONGSWORD, ItemID.BR_VESTAS_LONGSWORD,
        ItemID.VESTAS_LONGSWORD_BH),
    VESTA_S_SPEAR(50, ItemID.VESTAS_SPEAR, ItemID.VESTAS_SPEAR_BH),
    VOIDWAKER(50, ItemID.VOIDWAKER, ItemID.BR_VOIDWAKER),
    VOLATILE_NIGHTMARE_STAFF(55, ItemID.NIGHTMARE_STAFF_VOLATILE,
        ItemID.BR_NIGHTMARE_STAFF_VOLATILE),
    WEBWEAVER_BOW(50, ItemID.WILD_CAVE_WEBWEAVER_CHARGED),
    ZAMORAK_GODSWORD(50, ItemID.ZGS, ItemID.ZGSG),
    ZARYTE_CROSSBOW(75, ItemID.ZARYTE_XBOW, ItemID.BR_ZARYTE_XBOW),
    ;

    private static final Map<Integer, SpecWeapon> BY_ITEM_ID = new HashMap<>();

    static
    {
        for (SpecWeapon weapon : values())
        {
            for (int itemId : weapon.itemIds)
            {
                BY_ITEM_ID.put(itemId, weapon);
            }
        }
    }

    private final int costPercent;
    private final int[] itemIds;

    SpecWeapon(int costPercent, int... itemIds)
    {
        this.costPercent = costPercent;
        this.itemIds = itemIds;
    }

    /**
     * The entry for a worn item id, or null when that item has no special
     * attack.
     */
    static SpecWeapon forItemId(int itemId)
    {
        return BY_ITEM_ID.get(itemId);
    }
}
